### ISSUE TITLE
Không thể dùng được AIO tool 

### ISSUE THREAD

**Issue by zerorihs** [KenKout/schedule_hcmut_lecturer#1]
Trước thì mình có dùng và hoạt động bình thường. Sau đợt update thì tuy là không cần chọn khoảng thời gian nhưng công cụ lại không hoạt động. 
![Screenshot 2024-08-29 084359](https://github.com/user-attachments/assets/6f677412-e5e7-4338-a0bb-6c3728428780)
![Screenshot 2024-08-29 084347](https://github.com/user-attachments/assets/ab6b5f37-f276-420a-b721-9eaa56f25c6e)

**Comment by KenKout** [comment]
Mình có update rồi á, bạn Ctrl+Shift+F5 để reset cache nhé
